name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.0

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib test example

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings lib test example
